#!/usr/bin/env python3
"""
Convert legacy PHP files to modern HTML5
Replaces PHP templating with complete HTML5 pages
"""

import os
import re
import glob
from pathlib import Path

def get_html_template(title="Infant Botulism Treatment and Prevention Program"):
    """Generate modern HTML5 template"""

    template = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TITLE_PLACEHOLDER</title>
    <link rel="stylesheet" href="/css/modern-styles.css">
</head>
<body>
    <!-- Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-XXXXXXXXXX'); // Update with GA4 ID
    </script>

    <!-- Page Header -->
    <header class="page-header">
        <div class="header-content">
            <div class="header-logo">
                <img src="/images/cdph_logo.png" alt="California Department of Public Health Logo">
            </div>
            <div class="header-text">
                <div class="header-title">Infant Botulism Treatment and Prevention Program</div>
                <div class="header-subtitle">California Department of Public Health</div>
            </div>
        </div>
    </header>

    <!-- Main Navigation -->
    <nav class="main-nav">
        <button class="menu-toggle" aria-label="Toggle navigation menu" aria-expanded="false">
            ☰
        </button>
        <ul class="nav-menu">
            <!-- Navigation generated by JavaScript -->
        </ul>
    </nav>

    <!-- Main Content -->
    <main class="page-content">
        <div class="content-main">
CONTENT_PLACEHOLDER
        </div>
    </main>

    <!-- Page Footer -->
    <footer class="page-footer">
        For non-urgent questions and comments, please email<br>
        <a href="mailto:ibtpp@infantbotulism.org">ibtpp@infantbotulism.org</a><br>
        <br>
        <span style="font-size: 10px;">(The entire contents of this website are &copy; 2010 by the California Department of Public Health)</span>
    </footer>

    <!-- JavaScript -->
    <script src="/js/navigation.js"></script>
</body>
</html>'''

    template = template.replace('TITLE_PLACEHOLDER', title)
    return template

def extract_content_from_php(php_content, filepath):
    """Extract main content from PHP file, removing template includes"""

    # Remove opening template include
    content = re.sub(r'<\?php\s+require\(["\']\.\.?/scripts/template-start\.php["\']\);\s*\?>', '', php_content, flags=re.IGNORECASE)

    # Remove closing template include
    content = re.sub(r'<\?php\s+require\(["\']\.\.?/scripts/template-end\.php["\']\);\s*\?>', '', content, flags=re.IGNORECASE)

    # Remove emergency banner PHP code from index pages
    content = re.sub(
        r'<\?php\s*\$myFile\s*=\s*["\']contact/emergency["\'];.*?EOT;\s*\}\s*\?>',
        '',
        content,
        flags=re.DOTALL | re.IGNORECASE
    )

    # Clean up any remaining PHP tags (but preserve content)
    # Be careful with this - only remove simple PHP tags
    content = re.sub(r'<\?php\s*\?>', '', content)

    # Clean up excessive whitespace
    content = re.sub(r'\n\n\n+', '\n\n', content)
    content = content.strip()

    # Wrap content if it's not already in a proper structure
    # Most pages have table rows that need to be in a table
    if '<tr>' in content or '<td' in content:
        # Check if content starts with table row
        if content.strip().startswith('<tr'):
            # Wrap in table
            content = f'<table cellpadding="0" cellspacing="0" border="0" style="width: 100%;">\n{content}\n</table>'

    return content

def update_file_extensions_in_content(content):
    """Update .php extensions to .html in links"""
    # Update internal links
    content = re.sub(r'\.php(["\'\s>])', r'.html\1', content)
    # Fix any double extensions
    content = re.sub(r'\.html\.html', r'.html', content)
    return content

def clean_html_content(content):
    """Clean and modernize HTML content"""

    # Remove table wrapper artifacts from template system
    # These are leftover from the old template-start.php structure
    content = re.sub(r'<table[^>]*>\s*<tr>\s*<td class="title"[^>]*>', '<h1 class="section-header">', content, flags=re.IGNORECASE | re.DOTALL)
    content = re.sub(r'</td>\s*</tr>\s*<tr>\s*<td class="main"[^>]*>', '</h1>\n', content, flags=re.IGNORECASE | re.DOTALL)

    # Clean up orphaned table row/cell tags from template boundaries
    content = re.sub(r'^\s*<td class="title"[^>]*>', '<h1 class="section-header">', content, flags=re.IGNORECASE)
    content = re.sub(r'</td>\s*</tr>\s*<tr>\s*<td class="main"[^>]*>', '</h1>\n', content, flags=re.IGNORECASE | re.DOTALL)
    content = re.sub(r'^\s*</tr>\s*$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    content = re.sub(r'^\s*<td class="main"[^>]*>\s*$', '', content, flags=re.MULTILINE | re.IGNORECASE)
    content = re.sub(r'^\s*</td>\s*$', '', content, flags=re.MULTILINE | re.IGNORECASE)

    # Replace old-style table attributes with modern equivalents
    content = re.sub(r'cellpadding=(\d+)', r'cellpadding="\1"', content)
    content = re.sub(r'cellspacing=(\d+)', r'cellspacing="\1"', content)
    content = re.sub(r'border=(\d+)', r'border="\1"', content)
    content = re.sub(r'valign=(\w+)', r'valign="\1"', content)
    content = re.sub(r'align=(\w+)', r'align="\1"', content)
    content = re.sub(r'width=(\d+)', r'width="\1"', content)
    content = re.sub(r'height=(\d+)', r'height="\1"', content)
    content = re.sub(r'rowspan=(\d+)', r'rowspan="\1"', content)
    content = re.sub(r'colspan=(\d+)', r'colspan="\1"', content)

    # Clean up excessive blank lines
    content = re.sub(r'\n\n\n+', '\n\n', content)

    # Update file extensions in links
    content = update_file_extensions_in_content(content)

    return content.strip()

def convert_php_file(php_file_path, output_base_dir=None):
    """Convert a single PHP file to HTML"""

    # Read PHP file
    with open(php_file_path, 'r', encoding='utf-8', errors='ignore') as f:
        php_content = f.read()

    # Extract content
    content = extract_content_from_php(php_content, php_file_path)

    # Clean content
    content = clean_html_content(content)

    # Get title from filename or content
    title = "Infant Botulism Treatment and Prevention Program"

    # Generate HTML
    html_template = get_html_template(title)
    html_output = html_template.replace('CONTENT_PLACEHOLDER', content)

    # Determine output path
    if output_base_dir:
        rel_path = os.path.relpath(php_file_path, '/home/user/ibtpp')
        output_path = os.path.join(output_base_dir, rel_path)
    else:
        output_path = php_file_path

    # Change extension to .html
    output_path = output_path.replace('.php', '.html')

    # Create directory if needed
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Write HTML file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_output)

    return output_path

def find_all_php_files(base_dir='/home/user/ibtpp'):
    """Find all PHP files that need conversion"""

    php_files = []

    # Directories to include
    include_dirs = [
        '',  # root
        'general',
        'physician',
        'pharmacist',
        'laboratorian',
        'parent',
        'contact',
        'readings',
        'history',
    ]

    # Files to exclude
    exclude_files = [
        'phpinfo.php',
        'template-start.php',
        'template-end.php',
        'template-start-printable.php',
        'template-end-printable.php',
        'ws.php',
        'home.php',
    ]

    for dir_name in include_dirs:
        search_path = os.path.join(base_dir, dir_name, '*.php')
        for php_file in glob.glob(search_path):
            filename = os.path.basename(php_file)
            if filename not in exclude_files and 'frame' not in filename:
                php_files.append(php_file)

    return sorted(php_files)

def main():
    """Main conversion process"""

    print("PHP to HTML5 Conversion Tool")
    print("=" * 50)

    base_dir = '/home/user/ibtpp'

    # Find all PHP files
    php_files = find_all_php_files(base_dir)

    print(f"\nFound {len(php_files)} PHP files to convert")
    print("-" * 50)

    # Convert each file
    converted = []
    errors = []

    for php_file in php_files:
        try:
            output_file = convert_php_file(php_file)
            converted.append(output_file)
            rel_path = os.path.relpath(php_file, base_dir)
            print(f"✓ Converted: {rel_path}")
        except Exception as e:
            errors.append((php_file, str(e)))
            print(f"✗ Error: {php_file} - {e}")

    # Summary
    print("\n" + "=" * 50)
    print(f"Conversion complete!")
    print(f"Successfully converted: {len(converted)} files")

    if errors:
        print(f"Errors: {len(errors)} files")
        print("\nFiles with errors:")
        for php_file, error in errors:
            print(f"  - {php_file}: {error}")

    return len(errors) == 0

if __name__ == '__main__':
    success = main()
    exit(0 if success else 1)
